### PR TITLE
Refactor `Dotenv#with`

### PR DESCRIPTION
**Pull request by teoljungberg**
Use `reduce` instead of `tap` + `each`

### CODE REVIEW

**Comment by teoljungberg** [comment]
I see that `inject` is used elsewhere in the code, do you want me to rename my `reduce` to `inject`?

**Comment by bkeepers** [comment]
This was actually changed in https://github.com/bkeepers/dotenv/pull/130#discussion-diff-16292014. I'd love your thoughts on that conversation.

**Comment by teoljungberg** [comment]
`each` + `tap` is essentially the same as `each_with_object`, so I undetstand their critique. Though I personally prefer `inject` because it's usability. It's interesting why the Ruby Rouges bashed in the use of it, I think it's a perfect example on when to use `inject`. Could you share some light on that?

Sidebar - I prefer the name `reduce` over `inject` because you have a dataset that you are reducing down into something else, which makes more sense in my head than injecting something into our dataset `</sidebar>`

**Comment by bkeepers** [comment]
> I think it's a perfect example on when to use `inject`. Could you share some light on that?

Initially they critiqued it, but then they came around to saying that this was probably an appropriate use. 

Personally, I much prefer `reduce`/`inject` over anything else. And I'm cool with switching everything to `reduce`.

**Comment by teoljungberg** [comment]
Agreed.
If you want to merge my PR, do you want me to rename `reduce` to `inject` to match the other use of it?

**Comment by bkeepers** [comment]
:+1:

**Pull request merged**
