### PR TITLE
Prepare for 2.0 beta release

### PR DESCRIPTION
**Pull request by bkeepers**
https://github.com/bkeepers/dotenv/pull/159 adds back support for `.env.#{Rails.env}` that was removed in /cc https://github.com/bkeepers/dotenv/pull/95, so I'm going to bump the major version to indicate the change in functionality and push out a beta release to make sure there are no major issues with it.

Once this is released, I will probably deprecate the `dotenv-deployment` gem (or see if someone else wants to maintain it).

### CODE REVIEW

**Comment by bkeepers** [comment]
2.0.0.beta gem is released. I'de love help testing it:

```
gem "dotenv-rails", "2.0.0.beta", group: ["development", "test"]
```

**Comment by rypit** [comment]
:+1: This works for me in Rails 3.2.16 with `RAILS_ENV=production`, with proper hierarchy so it seems to address bkeepers/dotenv-deployment/issues/13, too.

**Comment by cyrusstoller** [comment]
+1

**Comment by bkeepers** [comment]
2.0 has been pushed to Rubygems. Enjoy!

**Pull request merged**
