### PR TITLE
Adopt rubocop styling

### PR DESCRIPTION
**Pull request by cshaffer**
Greetings! Big fan of dotenv. In hopes of enabling a consistent code style going forward, this PR includes:
* Development dependency on rubocop
* Initial autocorrections
* New .rubocop_todo.yml file to track existing offenses requiring
manual attention

The initial autocorrections are based on default config of rubocop. If, for example, you prefer double quoted strings, certain files to be ignored, or any other special config, let me know and I'd be happy to adjust them.

The .rubocop_todo.yml file kept track of all the offenses that rubocop couldn't automatically fix, things including line length to cyclomatic complexity. If you would like, I would be willing to go through each pending offense and address accordingly as well.

No worries if rubocop isn't for you, in which case feel free to close. :smile:

### CODE REVIEW

**Comment by bkeepers** [comment]
I would definitely be interested in adding rubocop! What would you think about making the config match the [GitHub Ruby Style Guide](https://github.com/styleguide/ruby)?

**Comment by cshaffer** [comment]
Great idea! Since the Github style guide overlaps with bbatsov/ruby-style-guide, which is what rubocop is implemented against, it was no problem.  In addition to preferring double quoted strings and hash rockets, I also got all the lines < 80.  Let me know if you think I missed something.

**Comment by cshaffer** [comment]
@bkeepers I had some time so I took this a tad further, let me know if I was a bit presumptuous with the way I resolved some of the rubocop offenses and I can revert;  I can also split these up into separate commits/PRs if you'd prefer.

Now all that would be left is some refactoring of `Parser#call`, adding some class documentation, and possibly ignoring/changing file names to snake_case.

**Comment by bkeepers** [comment]
Looks pretty good to me!

**Comment by cshaffer** [comment]
Alright, I think that's it! Ready when you are @bkeepers.  Let me know if you'd like anything changed or the commits squashed. Thanks!

**Comment by bkeepers** [comment]
Thanks!

**Pull request merged**
