### PR TITLE
Add gpg support

### PR DESCRIPTION
**Pull request by sheax0r**
This adds the capability for dotenv to read .env.gpg files.

### CODE REVIEW

**Comment by sheax0r** [comment]
@bkeepers thoughts on this?

**Comment by bkeepers** [comment]
This is really interesting. I'm not sure I want to support this as a first-class feature, but I'm up for talking more about it.

Is there a way we can build this as an extension and release it as a separate gem (like `dotenv-gpg`)?

**Comment by sheax0r** [comment]
Hey there @bkeepers - thanks for getting back to me. I don't see why not, although it might need some appropriate places to hook into - eg, `Dotenv.default_files` and `Environment.read`. 

A simple implementation would be something like just refactoring dotenv to have those methods, doing what they currently do, and then writing a `dotenv-gpg` gem that requires dotenv and monkeypatches those methods. Is this reasonable? If you have better architectural ideas on this, I'm open to suggestions.

Does dotenv currently have a way of handling loading of extensions? ie, dotenv could do something like check for existence of any "dotenv-*" gems when it starts up, and require them if they're available. Without this or something like it, I think we'd need to create a different executable.

**Comment by sheax0r** [comment]
... Thinking more about this, and we can definitely do better than monkeypatching, to be less brittle if core code changes. I guess it's just a question of "does dotenv already have a way to do extensions? or should I write one?"

**Comment by bkeepers** [comment]
> does dotenv already have a way to do extensions? or should I write one?

It does not. I'd love to explore what that would look like. Have at it!

**Comment by sheax0r** [comment]
Closing this in favour of https://github.com/bkeepers/dotenv/pull/213

**Pull request closed without merging**
