### PR TITLE
Fix multiline value parsing regressions reported in v2.3.0

### LINKED ISSUE #343: Parse multiline values
@joelvh tonight I had to revert #318 and #329 as #318 introduced a parsing regression (#336, #339, #341). We would be happy to review a follow up PR that re-introduces the feature and passes the regression tests I added in https://github.com/bkeepers/dotenv/pull/340/commits/b023c9b0e8b0948e44e42f9ee74ff7d6f24fa68a and https://github.com/bkeepers/dotenv/pull/340/commits/294ab7bce28b6d3d946b7fdfa7e919514cffdda9 and maybe adds a few more tests.

### PR DESCRIPTION
**Pull request by joelvh**
Fixes #343
Fixes #344

### CODE REVIEW

**Comment by joelvh** [comment]
Thanks! Hope this resolves things sufficiently for everyone.

**Comment by trevorcreech** [comment]
@cadwallion would it be possible to get a version bump so this change shows up in rubygems.org?

**Comment by cadwallion** [comment]
I'll get a version bump released tonight!

**Comment by cadwallion** [comment]
This was shipped in version 2.5.0 a few minutes ago.

**Comment by trevorcreech** [comment]
Thank you!

**Pull request merged**
