### PR TITLE
Unescape values correctly

### LINKED ISSUE #207: Some escaped '$' characters are not unescaped
Reported by @BeattieM in https://github.com/bkeepers/dotenv/pull/203, there are a few instances where escaped `$` doesn't get unescaped:

```
FOO="bar\$"
FOO="\$\$"
```

### PR DESCRIPTION
**Pull request by sorah**
ugly but fixes #207

### CODE REVIEW

**Comment by sorah** [comment]
I guess there are still remaining corner cases...

**Comment by sorah** [comment]
rubocop fails... I'll fix later

**Comment by bkeepers** [comment]
Thanks for the pull request! Sorry for the delay in responding. Would you be interested in merging master and fixing the merge conflicts?

**Comment by bkeepers** [comment]
Actually, it looks like this is fixed by https://github.com/bkeepers/dotenv/pull/222

**Pull request closed without merging**
