### PR TITLE
Existing variable takes precendence when performing substitution

### PR DESCRIPTION
**Pull request by jcechace**
See issue #312

### CODE REVIEW

**Comment by jcechace** [comment]
Is this project actively maintained?

**Comment by siegy22** [comment]
Hey @jcechace..

@bkeepers can't maintain this project because he doesn't have the time to do so 😐

**Comment by cadwallion** [comment]
:wave: @jcechace !

There's a new trio of maintainers for dotenv as of this week, as mentioned in #326 . I'll be reviewing this PR and the issue it came from shortly.  Thank you for this contribution, and am sorry this PR languished as long as it did!

**Comment by cadwallion** [comment]
This makes sense, merging in.  Thank you for the contribution!

**Comment by jonmagic** [comment]
We'll be cutting a new release next week that will include the changes from this PR.

**Pull request merged**
