### PR TITLE
don't load .env.local in rails' test environment

### PR DESCRIPTION
**Pull request by siegy22**
In my opinion, the .env.local should not overwrite .env.test
variables. When using .env.local for tests, the tests are not
transparent and can't be executed for example on a CI server.

As the documentation says, the `.env.local` is here for **local**
overwrites. They should not overwrite a test specific variable. Tests
should be run on every machine in every environment and shouldn't
require any specification of environment variables. (My opinion)

If the .env.local is needed in the test environment, it can be loaded in the test/spec helper:
```ruby
# test/test_helper.rb
...
Dotenv.load(Rails.root + "env.local")
```

### CODE REVIEW

**Comment by siegy22** [comment]
I am struggling with the tests..

I created a second test file to test the dotenv-rails in development mode. But it seems like the Railtie is only initialized once.. What do you think about the tests, what would be the best way to do this?

**Comment by bkeepers** [comment]
Hey @siegy22, thanks for the pull request! I agree that this matches expected behavior.

> I created a second test file to test the dotenv-rails in development mode. But it seems like the Railtie is only initialized once.. What do you think about the tests, what would be the best way to test this?

Railties are indeed only initialized once. One idea is to extract the paths to their own method (e.g. `dotenv_load_paths`, and test just that method with different environments.

**Comment by siegy22** [comment]
I updated it and fixed the tests, I hope that way it's okay for you. :grin:
I saw that you fixed the build, and dropped ruby 1.9 support  (🙏 🙏!) rebased that again into my branch, now the build should no longer fail.

**Comment by siegy22** [comment]
@bkeepers did you see that I updated that one? 😁

**Comment by siegy22** [comment]
I rebased once again and adjusted all the tests to the new circumstances.

**Comment by siegy22** [comment]
@bkeepers ping :grin:

**Comment by siegy22** [comment]
:tada: :shipit:

**Comment by bkeepers** [comment]
Thanks @siegy22!

**Comment by chuckd** [comment]
This is completely unexpected behaviour for me. I've run into .env.local not loading in test env a number of times and always assumed it was some bug due to local misconfiguration, not an intentional choice in dotenv-rails! I don't understand the rationale in this PR, for example "can't be executed for example on a CI server": why would you have an .env.local on your CI server? Anyway not a big deal now I know about it, just create an extra .env.test.local with a copy of the env var.

**Comment by jakedouglas** [comment]
I don't understand this either. 

> Tests should be run on every machine in every environment and shouldn't require any specification of environment variables.

Probably the most common example of this idea not holding water is that most Rails applications require a database, and the URL of that database may vary between different developer machines, and between developer machines and a CI service. Given this PR, if a developer happens to have a database setup that doesn't match the application's defaults (common), they need to specify the database URL in both `.env.local` _and_ `.env.test.local` in order to do local development comprehensively development.

You could argue that every application should come with a `docker-compose.yml` and so on, such that external service URLs are always consistent, but this is clearly outside of the scope of what dotenv should be prescribing.

**Comment by lukeredpath** [comment]
I've also just run into this issue and don't understand the rationale behind it. It was unexpected and confusing. The proposed workaround doesn't help if you have an initialiser that calls `Dotenv.require_keys` as this will be loaded before you have a chance to call `Dotenv.load` in your test helper and will raise an error, meaning the only workaround is to ensure you have a `.env.test` file with your required keys.

IMO this change should be reverted and `.env.local` should always be loaded in any environment.

**Comment by codyrobbins** [comment]
I just need to pile on and say that this change is nonsensical, frustrating, and unnecessary and the original rationale behind it doesn’t make any sense to me.

**Comment by ktimothy** [comment]
Excuse me, @bkeepers, why is this piece of illogical code, which was never discussed with anyone, still not reverted?

**Comment by siegy22** [comment]
It's been a while. While I agree with most of you guys, I think it mostly depends on how you use `.env.local`. 
We mostly used the `.env.local` for overrides that were just relevant when running the application in the development or production mode. Thus would override configurations of the `.env.test` file. Our `.env.test` was pretty much defining everything to run the tests on every machine (developers and CI) and didn't include things like a database url because we agreed on a default so every developer could start developing and testing without having to configure a lot of things.

I only see/hear the people here that don't agree with this behaviour because obviously it's been changed with this PR.
No idea how many people agree with this behaviour as we don't hear/see them 😄 

However, I feel that this can be reverted as it **is** a less-opinionated implementation to load the `.env.local` in the tests. 
No hard feelings 😊

**Pull request merged**
