### PR TITLE
Support Rails < 6.2

### PR DESCRIPTION
**Pull request by JuanitoFatas**
My rails application (blog) works with this patch.

### CODE REVIEW

**Comment by siegy22** [comment]
@cadwallion Would you mind taking a look at this?

**Comment by siegy22** [comment]
I don't know why this patch is needed. There's no rails release with version `6.1.x`? So this "patch" as of today doesn't do anything 😄 

Can you explain what your problem was, why you introduced this change?

**Comment by JuanitoFatas** [comment]
Oh I am terribly sorry. I always run my personal project on Rails master, which is now `6.1.0.alpha`. I understand if you do not want this patch now. Feel free to close this.

**Comment by siegy22** [comment]
Well this temporarily fixes it, but I'd rather just do `gem.add_dependency "railties", ">= 3.2"` (without a max version) so you won't run into any problems on future releases too.. 

Because if rails 6.1.0 will be released, they will most likely bump the version to `6.2.0.alpha`, which would break this version constraint yet again.

**Comment by JuanitoFatas** [comment]
I followed the convention from last time we bumped this: https://github.com/bkeepers/dotenv/pull/370. I‘m up for the `>= 3.2` approach 👍

**Pull request merged**
