### PR TITLE
Add overload option for the CLI

### PR DESCRIPTION
**Pull request by AhmedKamal20**

### CODE REVIEW

**Comment by bkeepers** [comment]
Hi @AhmedKamal20, thanks for the pull request! There are a couple lint failures here, but otherwise it looks good.

What would you think about renaming the option to `-f`/`--force`? That feels more consistent with other command line utilities to me.

**Comment by AhmedKamal20** [comment]
@bkeepers Thank you, I fixed the lint errors
And about `-f`, Yeah I considered that, but it's already being used on
`-f FILES, List of env files to parse`

**Comment by bkeepers** [comment]
@AhmedKamal20 thanks, I'll get a release out soon with this feature.

**Comment by amitsaxena** [comment]
@bkeepers do you plan on making a new release anytime soon? Looking forward to use this feature. :)

**Comment by bkeepers** [comment]
2.8.0 is out with this change. Enjoy!

**Comment by amitsaxena** [comment]
Thanks a lot @bkeepers 🌟

**Pull request merged**
