### PR TITLE
Fix for rspec rake tasks initializing in development

### LINKED ISSUE #219: Rake tasks in Rails always initialized in "development"
`rails 4.2.1`
`dotenv-rails 2.0.2`
`dotenv 2.0.2`

files: `.env.development` & `.env.test` with a subset of vars

`rake spec` has `.env.development` vars only. Again, my `.env.test` is a subset, so maybe new vars would be set too, but existing ones are not overwritten. In any case, I only want the `.env.test` config, so overwriting wouldn't solve the issue fully.

Not sure why #45 was closed. Am I missing something?

### PR DESCRIPTION
**Pull request by bkeepers**
This fixes #219, which causes Rails apps to always be initialized in development when being loaded from rake, by adding a hack that sets `RAILS_ENV=test` when `rake spec` is being run.

Rails [already includes a hack](https://github.com/rails/rails/blob/56ca2061df83a307943a0ffdfe6f5f4ed5846cf7/railties/lib/rails/test_unit/railtie.rb#L3-L5) like this, which will set `RAILS_ENV=test` when running `rake test`. This hack used to be loaded when requiring `rails/all`, but https://github.com/rails/rails/pull/10256 moved to to only be loaded when requiring `test_unit/railtie`. So, deally, rspec would copy this behavior when loading the [rspec railtie](https://github.com/rspec/rspec-rails/blob/master/lib/rspec-rails.rb).

I need to figure out a way to test this. I would appreciate any ideas for how to do that easily. The only thing I can think is to add a couple bare-bones Rails apps to the test suite that have different dependencies configured. :disappointed: 

/cc @bitherder

### CODE REVIEW

**Comment by bitherder** [comment]
This won't immediately work for us in two cases: 1) we often run just `rake` with the `default` task requiring `spec`; and 2) we (for no good reason) have specs run from tasks named things like `test:backend`. Of course, we can change 2) to use `spec:backend`, but 1) will continue to be a problem.

**Comment by skaes** [comment]
@bitherder actually, rails already takes care of 'default' and 'test' tasks

**Comment by bitherder** [comment]
@bkeepers, what do you think about merging this?

**Comment by bitherder** [comment]
See rejection of pull request to `rspec-rails`: https://github.com/rspec/rspec-rails/pull/1651

**Pull request merged**
